// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-02-26 22:13:14.592419 -0800 PST m=+0.022316266

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Binh Nguyen",
            "url": "http://www.swagger.io/support",
            "email": "ntbinh106@gmail.com"
        },
        "license": {
            "name": "MIT Licensed",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/eks/list-clusters": {
            "get": {
                "description": "get string by GET",
                "produces": [
                    "application/json"
                ],
                "summary": "List EKS Clusters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routers.AccountListClusterOutput"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "get string by GET",
                "produces": [
                    "application/json"
                ],
                "summary": "API Healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routers.APIStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routers.APIStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "routers.AccountListClusterOutput": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                },
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routers.ListClusterOutput"
                    }
                },
                "metadata": {
                    "type": "object",
                    "$ref": "#/definitions/routers.AccountMetadata"
                }
            }
        },
        "routers.AccountMetadata": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "routers.ListClusterOutput": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "The Unix epoch timestamp in seconds for when the cluster was created.",
                    "type": "string"
                },
                "name": {
                    "description": "The name of the cluster.",
                    "type": "string"
                },
                "region": {
                    "description": "AWS Region",
                    "type": "string"
                },
                "status": {
                    "description": "The current status of the cluster.",
                    "type": "string"
                },
                "version": {
                    "description": "The Kubernetes server version for the cluster.",
                    "type": "string"
                },
                "vpcId": {
                    "description": "Vpc ID of the cluster",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "Swagger Simple Kubernetes Dashboard",
	Description: "This is a API to interact with Kubernetes Services.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
