basePath: /api/v1
definitions:
  routers.APIStatus:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: ntbinh106@gmail.com
    name: Binh Nguyen
    url: http://www.swagger.io/support
  description: This is a API to interact with Kubernetes Objects
  license:
    name: MIT Licensed
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger Kubestorm API
  version: "1.0"
paths:
  /status:
    get:
      description: get string by GET
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.APIStatus'
      summary: API Healthcheck
schemes:
- http
- https
swagger: "2.0"
